### ISSUE TITLE
How do I find out a conversation id?

### ISSUE THREAD

**Issue by johnRivs** [ShyykoSerhiy/skyweb#16]
I wanna send a message to someone, but I have no idea how to get a conversation id.

**Comment by ShyykoSerhiy** [comment]
Skype uses interesting way of creating conversation ids: just prefix contact id with '8:'
Example:
contact that you've retrieved:

``` js
var contact = {
    "authorized": true,
    "blocked": false,
    "display_name": "skype skype",
    "id": "live:phantomzkype",
    "name": {
      "first": "skype",
      "surname": "skype",
      "nickname": "live:phantomzkype"
    },
    "type": "skype"
  };
```

Conversation id:

``` js
var conversationId = '8:' + contact.id; //8:live:phantomzkype
```

**Comment by johnRivs** [comment]
Gotcha.

Is there a way to search for a contact? Or should I filter through the contact list returned by `skyweb.contactsService.contacts` right after I login?

**Comment by ShyykoSerhiy** [comment]
Searching for contacts that aren't in yours contact list isn't currently implemented. So the only way for now is to filter skyweb.contactsService.contacts .
