### ISSUE TITLE
Change availability/status

### ISSUE THREAD

**Issue by findel** [ShyykoSerhiy/skyweb#17]
Hey! 

I've just started using this library for a bot. Is there any way yet to change the availability/status to online when running? 

Phil

**Comment by ShyykoSerhiy** [comment]
Hi, Phil. Do you mean changing status from "Hidden" to "Online"?

**Comment by findel** [comment]
Yeah, exactly.

**Comment by ShyykoSerhiy** [comment]
Currently no. I'll push the code for this later today(or tomorrow). Looks like it's easy to implement.

**Comment by ShyykoSerhiy** [comment]
Stay tuned. And thx for feature request.

**Comment by findel** [comment]
Thanks for responding so quickly!

**Comment by findel** [comment]
Thanks! :+1:
