### ISSUE TITLE
Unable to login for other Skype users after the first login success.

### ISSUE THREAD

**Issue by tolacambo** [ShyykoSerhiy/skyweb#2]
After I login the first user, it works fine. Then I try login different user, I go this message "Something went wrong!Failed to find pie or etm."

I think that this might have problem with cookie. It uses same cookie or connection object for each request.

Could you have a look at the issue?

**Comment by ShyykoSerhiy** [comment]
Keep in mind that using several accounts simultaneously may result in hitting the CAPTCHA wall. 
I don't recommend this.
