### ISSUE TITLE
Error 'Failed to find t inside.'

### ISSUE THREAD

**Issue by yakimko** [ShyykoSerhiy/skyweb#54]
Appeared today

**Comment by yakimko** [comment]
Not a bug. 
My skype account has been temporarily suspended.

**Comment by progval** [comment]
Was it suspended because of Skyweb?

**Comment by yakimko** [comment]
Dunno )
I make 3 login actions a day at the fixed time and send message to a group. MS didn't like it

**Comment by yakimko** [comment]
I confirmed my activity by SMS and now everything is going Ok

**Comment by progval** [comment]
Ah, yeah, I had those every single day the first week my bot was running
