### ISSUE TITLE
"Something went wrong!Failed to find t inside"

### ISSUE THREAD

**Issue by LAK132** [ShyykoSerhiy/skyweb#55]
What exactly does this error mean? I'm trying to work out why my bot wont start, but I cant seem to find any information on this error. I tried reinstalling Skyweb but that didn't help

**Comment by ShyykoSerhiy** [comment]
This usually happens if there are some problems with the login. 
You can try to change 
https://github.com/ShyykoSerhiy/skyweb/blob/master/dist/src/login.js#L50
to 
```js
rejectWithError(reject, 'Failed to find t inside.' + body);
```
that might provide you more info about what exactly had went wrong.

**Comment by progval** [comment]
According to #54, it may happen if your account is suspended.

**Comment by LAK132** [comment]
Account still functions, I can log in to Web Skype manually. 

Body gives:

http://pastebin.com/nGmYhHMR

**Comment by linjan** [comment]
@LAK132 what was the solution exactly?

**Comment by LAK132** [comment]
Login was failing because the account was trying to use 2 step auth (couldn't find the correct info when the 2 step page loaded, so it crashed). I just created another account that didn't have 2 step enabled
