### ISSUE TITLE
Bot crashing while attempting to approve login

### ISSUE THREAD

**Issue by LAK132** [ShyykoSerhiy/skyweb#57]
Bot is throwing "Something went wrong!Failed to find t inside" when the verification code is sent through, I assume this means the skyweb code is incapable of handling 2 step authentication?

**Comment by nistvan86** [comment]
I got the same issue trying to login.

**Comment by ShyykoSerhiy** [comment]
Check if your account has two factor auth. It's not supported for obvious reasons.

**Comment by nistvan86** [comment]
Actually it was easier. I had to prove that the account is mine using an SMS code. It's weird that using this API seemingly triggered a check, but I'm not sure.

**Comment by ShyykoSerhiy** [comment]
Yeah, it's not official API, so in development phase if you restart your app quite frequently, for Microsoft it will look like irregular activity on your account.

**Comment by ShyykoSerhiy** [comment]
Closing the issue because no fix is required( more like I don't see a way to fix this. )

**Comment by LAK132** [comment]
If the bot could simply not crash when the validation page comes up I would have thought that it would continue to work once it has been validated. If not, a more descriptive error code would be nice

**Comment by ShyykoSerhiy** [comment]
It shouldn't crash in the latest version. You can react on errors in latest version
```ts
Skyweb = require('skyweb');
var skyweb = new Skyweb();
const errorListener = (eventName: string, error: string) => {
    console.log(`${errorCount} : Error occured : ${error}`); 
};
skyweb.on('error', errorListener); //Adding error listener
```
