### ISSUE TITLE
0 : Error occured : Faile Failed to find t inside.

### ISSUE THREAD

**Issue by ghoshpushpendu** [ShyykoSerhiy/skyweb#60]
Showing this error while trying to authenticate . I need urgent support. Please help as soon as possible.

**Comment by ghoshpushpendu** [comment]
Is my ip address blocked . Cause i was using this module for last two weeks and this suddenly today stopped working with the error.

**Comment by ShyykoSerhiy** [comment]
Hi, it might be connected to the major http://www.theverge.com/2017/3/7/14841258/microsoft-account-outage-march-2017 outage on Microsoft side.

**Comment by ShyykoSerhiy** [comment]
You can try manually to login to web.skype.com in browser to see if it works.

**Comment by kissarat** [comment]
Яка, блядь, інформативна помилка. За бібліотеку дякую, хоч входити, в багатьох випадках прийдеться, все-таки запускаючи веб-скайп в webview
