### ISSUE TITLE
Skype token expires

### ISSUE THREAD

**Issue by CheweyZ** [ShyykoSerhiy/skyweb#63]
After ~24hours a skype auth token expires so every 24 hours I need to reboot the script and any longer it keeps sending the poll request to skype and erroring which dues to 24 hours of polling used 1.5GB of ram on the machine

Can a feature for auto renew occur 
Can be detected from when the skype polling returns the 403 forbidden message

Thanks

**Comment by fsarihan** [comment]
any Solution ?

**Comment by CheweyZ** [comment]
I've found a "solution" which is to use pm2 with the error listener as soon as one error occurs exit the process to which pm2 will notice the process shut and reboot the script, however, I've found not all logouts send errors sometimes the Skype account just goes offline with no error

This fix manages to keep the account loged in for upwards of a week although this not loged in bug is the only catch

**Comment by fsarihan** [comment]
Is pm2 something like  forever? How can i use this? Any example and thank you for helping me.

**Comment by CheweyZ** [comment]
It looks like there similar/identical

How To:
npm install pm2 -g
cd ./Where my script is
pm2 start myScript.js

pm2 list
will show all running process it's listening on
then 
pm2 logs myScript
can view output logs


Code:
```
  var errorListener = function(eventName, error) {
    console.log(errorCount + " : Error occured : " + error);
      console.log("Removing error listener && Starting reboot");
      skyweb.un('error', errorListener);
      skyweb.setStatus('Hidden');
      process.exit()
  };
```
