### ISSUE TITLE
"messagesCallback" is not invoked for Bot.

### ISSUE THREAD

**Issue by Akshansh93** [ShyykoSerhiy/skyweb#67]
Hello, I am unable to get the following response, if the message comes from a bot.
`message.resource.content + '. Cats will rule the World'`

I have added the bot to Skype Channel as contact via bot-framework and if I converse with the bot through chat-window, bot is replying.
But if i do 
` skyweb.sendMessage('28:botID', 'Hello'); `
The "Hello" and respective bot reply is shown in UI (chat-window) but the "_messagesCallback_" is not invoked.
**Expected Response**: Bot reply for 'Hello' + '. Cats will rule the World'
Can you please help me with this.
Note: Bot is replying normally in [web.skype.com](web.skype.com)

**Comment by ShyykoSerhiy** [comment]
Should be fixed in 0.4.0 .

**Comment by Akshansh93** [comment]
Thanks, it was fixed in 0.4.0 .
