### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by tuanmbs** [ShyykoSerhiy/skyweb#72]
Hi, When i install skypeweb, i have a error. My log:

> npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> skyweb@0.4.1 prepublish F:\MBS\Gekko\skypebot\skyweb
> tsc

src/login.ts(33,47): error TS2345: Argument of type '(previousValue: Promise<{}>, currentValue: any) => Promise<SkypeAccount>' is not assignable to parameter of type '(previousValue: Promise<SkypeAccount> | ((skypeAccount: SkypeAccount, resolve: any, reject: any) ...'.
  Types of parameters 'previousValue' and 'previousValue' are incompatible.
    Type 'Promise<SkypeAccount> | ((skypeAccount: SkypeAccount, resolve: any, reject: any) => void)' is not assignable to type 'Promise<{}>'.
      Type '(skypeAccount: SkypeAccount, resolve: any, reject: any) => void' is not assignable to type 'Promise<{}>'.
        Property 'then' is missing in type '(skypeAccount: SkypeAccount, resolve: any, reject: any) => void'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! skyweb@0.4.1 prepublish: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the skyweb@0.4.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tuan.nguyenhuu.TSC\AppData\Roaming\npm-cache\_logs\2018-03-07T03_55_44_592Z-debug.log

>

**Comment by phillipadsmith** [comment]
Any update on this @ShyykoSerhiy? Or way to access a previous version? Possible that releases can be tagged to make that easy?

**Comment by ShyykoSerhiy** [comment]
fixed in 0.4.2

**Comment by tuanmbs** [comment]
Ok, thanks
